// <auto-generated />
using System;
using Dashboard_MK4.Models.V2_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.Vehicle_
{
    [DbContext(typeof(Vehicle_Context))]
    [Migration("20200222123102_Dashboard_MK4.Models.V2_Models.Vehicle_Context")]
    partial class Dashboard_MK4ModelsV2_ModelsVehicle_Context
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.V2_Models.Vehicle", b =>
                {
                    b.Property<Guid>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_ID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Vehicle_ID = new Guid("00000000-0000-0000-0000-000000000002"),
                            Make = "Ford",
                            REG = "Eleanor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
