// <auto-generated />
using System;
using Dashboard_MK4.Models.V3_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.JobCard_TaskDescriptions_
{
    [DbContext(typeof(JobCard_TaskDescriptions_Context))]
    [Migration("20200512113528_Add_Vehicle_And_TaskDescriptionsV3")]
    partial class Add_Vehicle_And_TaskDescriptionsV3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.V2_Models.Vehicle", b =>
                {
                    b.Property<Guid>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_ID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.Client_Display_ID", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Client_DisplayID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Client_Display_ID");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JobCardV3", b =>
                {
                    b.Property<Guid>("JobCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("JobCardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientDisplayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobCardName")
                        .IsRequired()
                        .HasColumnName("JobCardName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("VehicleDisplayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VehicleV3Vehicle_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Vehicle_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobCardID");

                    b.HasIndex("ClientDisplayID");

                    b.HasIndex("VehicleDisplayID");

                    b.HasIndex("VehicleV3Vehicle_ID");

                    b.HasIndex("Vehicle_ID");

                    b.ToTable("JobCards");

                    b.HasData(
                        new
                        {
                            JobCardID = new Guid("00000000-0000-0000-0000-000000000012"),
                            JobCardName = "Clutch Replacement"
                        });
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.TaskDescriptionV3", b =>
                {
                    b.Property<Guid>("Task_Description_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Task_Description_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobCardIDForRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobCardV3JobCardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabourCost")
                        .HasColumnName("LabourCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartsPrice")
                        .HasColumnName("PartsPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalTaskCost")
                        .HasColumnName("TotalTaskCost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Task_Description_ID");

                    b.HasIndex("JobCardV3JobCardID");

                    b.ToTable("TaskDescriptions");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.VehicleV3", b =>
                {
                    b.Property<Guid>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_ID");

                    b.ToTable("Vehicles_V3");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.Vehicle_Display_ID", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Vehicle_ID_Display")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Vehicle_Display_ID");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JobCardV3", b =>
                {
                    b.HasOne("Dashboard_MK4.Models.V3_Models.Client_Display_ID", "ClientDisplay")
                        .WithMany()
                        .HasForeignKey("ClientDisplayID");

                    b.HasOne("Dashboard_MK4.Models.V3_Models.Vehicle_Display_ID", "VehicleDisplay")
                        .WithMany()
                        .HasForeignKey("VehicleDisplayID");

                    b.HasOne("Dashboard_MK4.Models.V3_Models.VehicleV3", "VehicleV3")
                        .WithMany()
                        .HasForeignKey("VehicleV3Vehicle_ID");

                    b.HasOne("Dashboard_MK4.Models.V2_Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_ID");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.TaskDescriptionV3", b =>
                {
                    b.HasOne("Dashboard_MK4.Models.V3_Models.JobCardV3", "JobCardV3")
                        .WithMany("TaskDescriptions")
                        .HasForeignKey("JobCardV3JobCardID");
                });
#pragma warning restore 612, 618
        }
    }
}
