// <auto-generated />
using System;
using Dashboard_MK4.Models.N_S_Models.NS_H20;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.NS_H20_
{
    [DbContext(typeof(NS_H20_Context))]
    [Migration("20210127182017_H20_Model")]
    partial class H20_Model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.N_S_Models.NS_H20.NS_H20", b =>
                {
                    b.Property<Guid>("NS_H20_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Litres_In_Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("NS_H20_ID");

                    b.ToTable("H20_Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
