// <auto-generated />
using System;
using Dashboard_MK4.Models.V2_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.JTFA_Client_
{
    [DbContext(typeof(JTFA_Client_Context))]
    partial class JTFA_Client_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.V2_Models.JTFA_Client", b =>
                {
                    b.Property<Guid>("JTFA_CLIENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notifications_Permission_Levels_Allowed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JTFA_CLIENT_ID");

                    b.ToTable("JTFA_Clients");

                    b.HasData(
                        new
                        {
                            JTFA_CLIENT_ID = new Guid("00000000-0000-0000-0000-000000000003"),
                            Email = "----------Daffyduckrules@WarnerBros.com ---------",
                            Name = "----------Daffy Duck------------",
                            Notifications_Permission_Levels_Allowed = "Yes",
                            PhoneNumber = "-----0000----"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
