// <auto-generated />
using System;
using Dashboard_MK4.Models.V2_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.Job_Card_
{
    [DbContext(typeof(Job_Card_Context))]
    partial class Job_Card_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.V2_Models.Job_Card", b =>
                {
                    b.Property<Guid>("JobCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Car")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Invoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCardID");

                    b.ToTable("JobCards");

                    b.HasData(
                        new
                        {
                            JobCardID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Car = "Toyota Hilux",
                            Date = new DateTime(2020, 1, 29, 16, 20, 10, 421, DateTimeKind.Utc).AddTicks(929),
                            Email = "blah@micarcentre.com",
                            Invoice = "SC 1000",
                            Mileage = "10000000000",
                            Name = "MICar Centre",
                            Notes = "Awe",
                            Phone = "021 558 4589",
                            REG = "CY",
                            Total = "R999999999999",
                            VIN = "DRUK"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
