// <auto-generated />
using System;
using Dashboard_MK4.Models.V3_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.JTFA_Invoice_
{
    [DbContext(typeof(JTFA_Invoice_Context))]
    [Migration("20200720080640_Add_Email_Recipeints_prop")]
    partial class Add_Email_Recipeints_prop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.V2_Models.JTFA_Client", b =>
                {
                    b.Property<Guid>("JTFA_CLIENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notifications_Permission_Levels_Allowed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JTFA_CLIENT_ID");

                    b.ToTable("JTFA_Client");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V2_Models.Vehicle", b =>
                {
                    b.Property<Guid>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_ID");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JTFA_Invoice", b =>
                {
                    b.Property<Guid>("JTFA_Invoice_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email_Recipients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INV_Number")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobcardV3JobCardID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JTFA_Invoice_ID");

                    b.HasIndex("JobcardV3JobCardID");

                    b.ToTable("JTFA_Invoice");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JobCardV3", b =>
                {
                    b.Property<Guid>("JobCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("JobCardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JTFA_CLIENT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobCardName")
                        .IsRequired()
                        .HasColumnName("JobCardName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("Vehicle_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobCardID");

                    b.HasIndex("JTFA_CLIENT_ID");

                    b.HasIndex("Vehicle_ID");

                    b.ToTable("JobCardV3");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.TaskDescriptionV3", b =>
                {
                    b.Property<Guid>("Task_Description_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Task_Description_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobCardIDForRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobCardV3JobCardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabourCost")
                        .HasColumnName("LabourCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartsPrice")
                        .HasColumnName("PartsPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalTaskCost")
                        .HasColumnName("TotalTaskCost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Task_Description_ID");

                    b.HasIndex("JobCardV3JobCardID");

                    b.ToTable("TaskDescriptionV3");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JTFA_Invoice", b =>
                {
                    b.HasOne("Dashboard_MK4.Models.V3_Models.JobCardV3", "JobcardV3")
                        .WithMany()
                        .HasForeignKey("JobcardV3JobCardID");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JobCardV3", b =>
                {
                    b.HasOne("Dashboard_MK4.Models.V2_Models.JTFA_Client", "JTFA_Client")
                        .WithMany()
                        .HasForeignKey("JTFA_CLIENT_ID");

                    b.HasOne("Dashboard_MK4.Models.V2_Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_ID");
                });

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.TaskDescriptionV3", b =>
                {
                    b.HasOne("Dashboard_MK4.Models.V3_Models.JobCardV3", "JobCardV3")
                        .WithMany("TaskDescriptions")
                        .HasForeignKey("JobCardV3JobCardID");
                });
#pragma warning restore 612, 618
        }
    }
}
