// <auto-generated />
using System;
using Dashboard_MK4.Models.V3_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard_MK4.Migrations.JTFA_Invoice_
{
    [DbContext(typeof(JTFA_Invoice_Context))]
    [Migration("20200722093304_Remove_Reference_Navigation_Property_JobCardV3_From_JTFA_Invoice_Type_And_Add_ForeignKey")]
    partial class Remove_Reference_Navigation_Property_JobCardV3_From_JTFA_Invoice_Type_And_Add_ForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard_MK4.Models.V3_Models.JTFA_Invoice", b =>
                {
                    b.Property<Guid>("JTFA_Invoice_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email_Recipients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INV_Number")
                        .HasColumnType("int");

                    b.Property<Guid>("JobCardID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JTFA_Invoice_ID");

                    b.ToTable("JTFA_Invoice");
                });
#pragma warning restore 612, 618
        }
    }
}
